"""add user_id and org_id to chat_sessions

Revision ID: 7ac4e971d9c1
Revises: d8c03515d311
Create Date: 2026-08-20 13:40:30.190473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac4e971d9c1'
down_revision: Union[str, Sequence[str], None] = 'd8c03515d311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('chat_sessions', sa.Column('org_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_chat_sessions_org_id'), 'chat_sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_org_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'org_id')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###
